"""
Interactive setup script for Supabase PostgreSQL configuration.
Helps generate .env file and test connection.
"""

import os
import sys
import secrets
from pathlib import Path
from urllib.parse import urlparse, quote_plus

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))


def print_header(text):
    """Print formatted header."""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70 + "\n")


def print_success(text):
    """Print success message."""
    print(f"✓ {text}")


def print_error(text):
    """Print error message."""
    print(f"✗ {text}")


def print_info(text):
    """Print info message."""
    print(f"ℹ {text}")


def generate_secret_key():
    """Generate a secure secret key."""
    return secrets.token_hex(32)


def validate_database_url(url):
    """Validate database URL format."""
    try:
        result = urlparse(url)
        if result.scheme != 'postgresql':
            return False, "URL must start with 'postgresql://'"
        if not result.hostname:
            return False, "Invalid hostname"
        if not result.username:
            return False, "Missing username"
        return True, "Valid"
    except Exception as e:
        return False, str(e)


def encode_password(password):
    """URL-encode password if it contains special characters."""
    special_chars = ['@', '#', '$', '%', '&', '/', '?', '=', '+']
    needs_encoding = any(char in password for char in special_chars)
    
    if needs_encoding:
        encoded = quote_plus(password)
        print_info(f"Password contains special characters. Encoded version: {encoded}")
        return encoded
    return password


def create_env_file():
    """Interactive .env file creation."""
    print_header("SUPABASE CONFIGURATION WIZARD")
    
    env_path = Path(__file__).parent / ".env"
    env_example_path = Path(__file__).parent / ".env.example"
    
    # Check if .env already exists
    if env_path.exists():
        print_info(f".env file already exists at: {env_path}")
        overwrite = input("Do you want to overwrite it? (y/N): ").strip().lower()
        if overwrite != 'y':
            print_info("Keeping existing .env file.")
            return str(env_path)
    
    print("\nLet's set up your Supabase PostgreSQL connection.\n")
    
    # Step 1: Generate JWT secrets
    print_header("STEP 1: Generate JWT Secrets")
    print("Generating secure secret keys...")
    secret_key = generate_secret_key()
    refresh_secret_key = generate_secret_key()
    print_success("Secret keys generated")
    
    # Step 2: Database URL
    print_header("STEP 2: Supabase Database Connection")
    print("Get your connection string from:")
    print("  Supabase Dashboard → Project Settings → Database → Connection String\n")
    
    print("Example formats:")
    print("  Direct: postgresql://postgres:PASSWORD@db.PROJECT_REF.supabase.co:5432/postgres")
    print("  Pooled: postgresql://postgres.PROJECT_REF:PASSWORD@aws-0-REGION.pooler.supabase.com:5432/postgres\n")
    
    while True:
        database_url = input("Enter your Supabase DATABASE_URL: ").strip()
        
        if not database_url:
            print_error("Database URL cannot be empty")
            continue
        
        valid, message = validate_database_url(database_url)
        if valid:
            print_success("Database URL format is valid")
            break
        else:
            print_error(f"Invalid URL: {message}")
            continue
    
    # Step 3: Optional configurations
    print_header("STEP 3: Optional Configurations")
    
    debug = input("Enable debug mode? (y/N): ").strip().lower() == 'y'
    elasticsearch_enabled = input("Enable Elasticsearch? (Y/n): ").strip().lower() != 'n'
    
    if elasticsearch_enabled:
        es_url = input("Elasticsearch URL (default: http://localhost:9200): ").strip()
        if not es_url:
            es_url = "http://localhost:9200"
    else:
        es_url = "http://localhost:9200"
    
    # Step 4: Create .env file
    print_header("STEP 4: Creating .env File")
    
    env_content = f"""# AI SOC Assistant Configuration
# Generated by setup_supabase.py

APP_NAME=AI SOC Assistant
DEBUG={str(debug).lower()}

# JWT Configuration
SECRET_KEY={secret_key}
REFRESH_SECRET_KEY={refresh_secret_key}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=15
REFRESH_TOKEN_EXPIRE_DAYS=7

# Database - Supabase PostgreSQL
DATABASE_URL={database_url}

# Kafka Integration
KAFKA_BROKER=localhost:9092
KAFKA_TOPIC_RAW_LOGS=raw-logs

# Elasticsearch
ELASTICSEARCH_URL={es_url}
ELASTICSEARCH_ENABLED={str(elasticsearch_enabled).lower()}

# LLM - Groq API (optional - for incident summaries)
GROQ_API_KEY=

# OAuth Providers (optional)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
OAUTH_REDIRECT_URI=http://localhost:8000/auth/callback

# CORS Configuration
CORS_ORIGINS=["http://localhost:3000","http://localhost:5173","http://localhost:8080"]
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print_success(f".env file created at: {env_path}")
    
    return str(env_path)


def test_connection():
    """Test database connection."""
    print_header("STEP 5: Testing Database Connection")
    
    try:
        from app.database import check_connection
        
        print("Attempting to connect to Supabase...")
        if check_connection():
            print_success("Database connection successful!")
            return True
        else:
            print_error("Database connection failed!")
            print_info("Please check your DATABASE_URL and ensure your Supabase project is active")
            return False
    except Exception as e:
        print_error(f"Connection test failed: {e}")
        return False


def check_migrations():
    """Check if migrations need to be run."""
    print_header("STEP 6: Database Migrations")
    
    try:
        from app.database import engine
        
        with engine.connect() as conn:
            result = conn.execute(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema = 'public' AND table_name = 'users'"
            )
            tables = list(result)
        
        if not tables:
            print_info("Database tables not found. You need to run migrations.")
            print("\nRun the following command:")
            print("  alembic upgrade head\n")
            return False
        else:
            print_success("Database tables found!")
            return True
            
    except Exception as e:
        print_error(f"Migration check failed: {e}")
        return False


def main():
    """Main setup function."""
    print("\n" + "=" * 70)
    print("  🚀 AI SOC ASSISTANT - SUPABASE SETUP WIZARD")
    print("=" * 70)
    
    # Step 1: Create .env file
    env_path = create_env_file()
    
    # Step 2: Test connection
    if not test_connection():
        print("\n" + "=" * 70)
        print_error("Setup completed with errors")
        print("=" * 70)
        print("\nTroubleshooting:")
        print("1. Verify your Supabase project is active")
        print("2. Check DATABASE_URL format")
        print("3. Ensure your password is correctly URL-encoded")
        print("4. Review SUPABASE_SETUP.md for detailed instructions")
        return 1
    
    # Step 3: Check migrations
    needs_migration = not check_migrations()
    
    # Success summary
    print_header("✓ SETUP COMPLETE")
    
    print("Configuration file created: " + env_path)
    print("Database connection: ✓ Working\n")
    
    if needs_migration:
        print("⚠ Next steps:")
        print("1. Run migrations: alembic upgrade head")
        print("2. Verify setup: python verify_supabase.py")
        print("3. Start server: uvicorn app.main:app --reload")
    else:
        print("✓ Next steps:")
        print("1. Verify setup: python verify_supabase.py")
        print("2. Start server: uvicorn app.main:app --reload")
        print("3. Visit API docs: http://localhost:8000/docs")
    
    print("\n📚 For detailed documentation, see: SUPABASE_SETUP.md")
    print("=" * 70 + "\n")
    
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(1)
    except Exception as e:
        print_error(f"Unexpected error: {e}")
        sys.exit(1)
